name: Thomas Amaro – The Official Site
favicon: null
layout_spectrum: 0.2143547
typography_spectrum: 0.9267724
title: Thomas Amaro
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#747477'
    - '#9F9FA1'
    - '#5A595B'
    - '#1E1E1E'
  brandStrength: 0.5746269
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
