name: Thomas Amaro
favicon: null
layout_spectrum: 0.2143547
typography_spectrum: 0.81982
title: Thomas Amaro
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#d7dcdf'
    - '#fdfffe'
    - '#71797c'
    - '#454d51'
  brandStrength: 0.0625
  lightness: 0.1809701
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
